// VS Code-style tab strip (used by the code panel and the bottom panel).
import type { ReactNode } from 'react'
import './Tabs.css'

export interface TabItem<T extends string> {
  id: T
  label: string
  /** Optional trailing badge, e.g. a problem count. */
  badge?: ReactNode
}

interface TabsProps<T extends string> {
  tabs: TabItem<T>[]
  active: T
  onChange: (id: T) => void
  /** Accessible name for the tab list. */
  label: string
  /** Extra controls rendered on the right of the strip. */
  actions?: ReactNode
}

export function Tabs<T extends string>({ tabs, active, onChange, label, actions }: TabsProps<T>) {
  return (
    <div className="tabs">
      <div role="tablist" aria-label={label} className="tabs__list">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            role="tab"
            type="button"
            id={`tab-${tab.id}`}
            aria-selected={tab.id === active}
            aria-controls={`tabpanel-${tab.id}`}
            tabIndex={tab.id === active ? 0 : -1}
            className="tabs__tab"
            onClick={() => onChange(tab.id)}
            onKeyDown={(e) => {
              if (e.key !== 'ArrowRight' && e.key !== 'ArrowLeft') return
              const i = tabs.findIndex((t) => t.id === active)
              const next = tabs[(i + (e.key === 'ArrowRight' ? 1 : tabs.length - 1)) % tabs.length]
              onChange(next.id)
              document.getElementById(`tab-${next.id}`)?.focus()
            }}
          >
            {tab.label}
            {tab.badge !== undefined && <span className="tabs__badge">{tab.badge}</span>}
          </button>
        ))}
      </div>
      {actions && <div className="tabs__actions">{actions}</div>}
    </div>
  )
}

/** Container for a tab's content; pairs with the ids generated by <Tabs>. */
export function TabPanel({ id, children }: { id: string; children: ReactNode }) {
  return (
    <div
      role="tabpanel"
      id={`tabpanel-${id}`}
      aria-labelledby={`tab-${id}`}
      className="tabs__panel"
    >
      {children}
    </div>
  )
}
