// Code panel: the circuit as OpenQASM 2.0 and as Qiskit Python.
// Both tabs are editable and synced both ways with the circuit and with each other
// (see codeSync.ts and PLAN.md → Sync rules / V2-1). Each tab has its own text, Monaco model,
// undo history and cursor.
import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react'
import { useProblemsStore } from '../../model/store'
import { useUiStore, type CodeTab } from '../../model/uiStore'
import { SkeletonGroup, SkeletonLines } from '../common/Skeleton'
import { TabPanel, Tabs } from '../common/Tabs'
import './CodePanel.css'
import { codeTextStores, editCode } from './codeSync'
import { ReplacedNotice } from './ReplacedNotice'
import { useRevealStore } from './revealStore'

// Monaco is large, so the editor is its own chunk, loaded after the workspace renders.
const CodeEditor = lazy(() => import('./CodeEditor'))

const TABS: { id: CodeTab; label: string }[] = [
  { id: 'qasm', label: 'QASM' },
  { id: 'qiskit', label: 'Qiskit' },
]

const EDITOR_PROPS: Record<CodeTab, { language: string; path: string; ariaLabel: string }> = {
  qasm: { language: 'qasm', path: 'circuit.qasm', ariaLabel: 'OpenQASM 2.0 code' },
  qiskit: { language: 'python', path: 'circuit.py', ariaLabel: 'Qiskit Python code' },
}

/** Grey lines shaped like a short program while Monaco loads. */
function EditorSkeleton() {
  return (
    <div className="code-panel__skeleton">
      <SkeletonGroup label="code editor">
        <SkeletonLines
          lines={9}
          widths={['34%', '46%', '0', '28%', '0', '22%', '40%', '36%', '30%']}
        />
      </SkeletonGroup>
    </div>
  )
}

/** Copies the active tab's code; the icon briefly turns into a check mark. */
function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const timer = useRef<number | undefined>(undefined)
  useEffect(() => () => window.clearTimeout(timer.current), [])

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      window.clearTimeout(timer.current)
      timer.current = window.setTimeout(() => setCopied(false), 1500)
    } catch {
      // Clipboard blocked (permissions / insecure context). Ctrl+C in the editor still works.
    }
  }

  const label = copied ? 'Copied' : 'Copy code'
  return (
    <button type="button" className="icon-button" onClick={copy} title={label} aria-label={label}>
      <span className={`codicon codicon-${copied ? 'check' : 'copy'}`} aria-hidden="true" />
    </button>
  )
}

export function CodePanel() {
  const tab = useUiStore((s) => s.codeTab)
  const setTab = useUiStore((s) => s.setCodeTab)
  const problems = useProblemsStore((s) => s.byTab[tab])
  const reveal = useRevealStore((s) => s.request)
  const clearReveal = useRevealStore((s) => s.clear)

  // The user's own text while they edit; regenerated by codeSync for changes from elsewhere.
  const code = codeTextStores[tab]((s) => s.text)
  const onChange = useCallback((text: string) => editCode(tab, text), [tab])

  return (
    <div className="code-panel">
      <Tabs
        tabs={TABS}
        active={tab}
        onChange={setTab}
        label="Code"
        actions={<CopyButton text={code} />}
      />
      <ReplacedNotice tab={tab} />
      <TabPanel id={tab}>
        <Suspense fallback={<EditorSkeleton />}>
          <CodeEditor
            value={code}
            onChange={onChange}
            markers={problems}
            reveal={reveal?.tab === tab ? reveal : null}
            onRevealed={clearReveal}
            {...EDITOR_PROPS[tab]}
          />
        </Suspense>
      </TabPanel>
    </div>
  )
}
